### ISSUE TITLE
2022-09 - current status of using gtest with NDK project

### ISSUE THREAD

**Issue by polishcode** [DanAlbert/GTestJNI#1]
Hello @DanAlbert,
I would like to ask what is the current/preferred way of using gtest with C++ part of the Android project?
Is this demo project still valid in order to achieve gtest-Android Studio integration for unit tests?
From my perspective, my C++ codebase:
- is crosscompiled for Android, Windows, iOS
- is based on cmake
- is integrated with gtest using cmake
- can be gtested on Windows from commandline
- cannot be gtested for Android either for gradle nor Android Studio (standard cmake gtest integration does not allow that)

What is the purpose/usage of sources\third_party\googletest\ in recent NDK releases?
Thank you!

**Comment by DanAlbert** [comment]
It's available in maven now: https://developer.android.com/jetpack/androidx/releases/test#junit-gtest_10_2

https://github.com/DanAlbert/ndk-app-template has usage examples. It's not entirely ready yet, but it's an improvement over what's in this repository. The issues that are preventing it from being more widely pushed are:

1. https://issuetracker.google.com/236913987
2. No docs
3. No samples

I'll push a patch here to update the README so that's more clear. Thanks for the reminder.

**Comment by DanAlbert** [comment]
Done.

**Comment by polishcode** [comment]
Great, thank you!
